### ISSUE TITLE
page hangs when editing/updating chapters

### ISSUE THREAD

**Issue by leroidejesa** [epicodus/textbook#4]
I get a 500 error on POST at `https://www.learnhowtoprogram.com/chapters/css/edit` after clicking chapter update button. Navigating to the *Table of contents* page via footer link, however, I see my changes are being saved. Did I break something by sliding the CSS course into that spot (as opposed to just adding it to the bottom)? Maybe the lessons are out of whack now? I tried changing the numbers accordingly.

**Comment by michaelrkn** [comment]
Ask Chris.

**Comment by kellywerks** [comment]
This is a known issue. It is in Pivotal for Learn How to Program tasks to review.  You didn't break anything.  Once you hit update, you can be assured it's updated and then navigate where you need to.

**Comment by chrisjoywebb** [comment]
This has been fixed with PR #5 .
